# -*- coding: utf-8 -*-
"""prepare_csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/160Psq2NK0-sB44JK-KnhdjopoZs0eQVr
"""

import os,cv2
import numpy as np
import pandas as pd

data_path = 'input'
data_dir_list = os.listdir(data_path)

class_labels={'adni_MRI':0,'adni_PET':1}

df = pd.DataFrame(columns=['img_names', 'labels', 'class_names'])

for dataset in data_dir_list:
    img_list=os.listdir(os.path.join(data_path, dataset))
    print ('Loading dataset-'+'{}\n'.format(dataset))
    label=class_labels[dataset]
    for img in img_list:
        img_name=os.path.join(data_path,dataset,img)
       # annotations.append([image_name,dataset,label])
        df = df.append({'img_names': img_name, 'labels': label,'class_names': dataset},ignore_index=True)

df.to_csv(os.path.join('annotations_2.csv'))

