# -*- coding: utf-8 -*-
"""embedding_visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1upo0Hj48t9Q6bNaoC5a5iRyx6b3q0ZCw
"""

import os,cv2
import numpy as np
from tqdm import tqdm
import pandas as pd
#import matplotlib.pyplot as plt
import pickle
import tensorflow as tf
from tensorboard.plugins import projector

tf.__version__

LOG_DIR = 'logs_2'
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

# metadata file
data = pd.read_csv('annotations_2.csv',usecols=['img_names', 'labels', 'class_names'])

metadata_file = open(os.path.join(LOG_DIR, 'metadata.tsv'), 'w')
metadata_file.write('Image_no\tClass\tName\n')

for num,label,name in zip(data.img_names,data.labels,data.class_names):
    metadata_file.write('{}\t{}\t{}\n'.format(num[-7:-4],label,name))
metadata_file.close()

#

with open('feature_vectors.pkl', 'rb') as f:
    feature_vectors = pickle.load(f)
#feature_vectors = np.loadtxt('feature_vectors_400_samples.txt')
print ("feature_vectors_shape:",feature_vectors.shape)
print ("num of images:",feature_vectors.shape[0])
print ("size of individual feature vector:",feature_vectors.shape[1])

features = tf.Variable(feature_vectors, name='features')

checkpoint = tf.train.Checkpoint(embedding=features)
checkpoint.save(os.path.join(LOG_DIR, "embedding.ckpt"))

config = projector.ProjectorConfig()
embedding = config.embeddings.add()

# The name of the tensor will be suffixed by `/.ATTRIBUTES/VARIABLE_VALUE v.imp or tf2 won't work`
embedding.tensor_name = "embedding/.ATTRIBUTES/VARIABLE_VALUE"

embedding.metadata_path =  'metadata.tsv'

projector.visualize_embeddings(LOG_DIR, config)

# tensorboard --logdir=logs_2 --port=6006

